version: '3.8'

# Development overrides
services:
  # API with development settings
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - Jwt__SecretKey=${JWT_SECRET_KEY}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      # Mount source code for live reload (uncomment if using dotnet watch)
      # - ./:/src
      # - ./appsettings.Development.json:/app/appsettings.Development.json
      - ./logs/api:/app/Logs
    ports:
      - "5000:5000"  # ONLY for development - direct API access/Swagger debugging