version: '3.8'

services:
  # .NET Web API Only (No Nginx - Direct access)
  olloapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olloapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/Logs
      - ./appsettings.Production.json:/app/appsettings.Production.json:ro
    restart: unless-stopped
    networks:
      - ollo-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  ollo-network:
    driver: bridge

volumes:
  logs:
    driver: local