version: '3.8'

services:
  # Nginx Reverse Proxy (Internal Only)
  nginx-proxy:
    build: ./nginx
    container_name: ollo-api-nginx-proxy
    restart: unless-stopped
    expose:
      - "80"  # Internal Docker network only
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - backend
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # API Service
  api:
    build: .
    container_name: ollo-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - Jwt__SecretKey=${JWT_SECRET_KEY}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - DB_PASSWORD=${DB_PASSWORD}
    expose:
      - "5000"  # Internal only, accessible via Docker network
    networks:
      - backend
    volumes:
      - ./logs/api:/app/Logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  backend:
    driver: bridge
    internal: true  # No external access

volumes:
  logs:
    driver: local