version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollolifestyle-api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - Jwt__SecretKey=${JWT_SECRET_KEY}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - shared-network
    volumes:
      - api-logs:/app/Logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  shared-network:
    external: true
    name: ollolifestyle-network

volumes:
  api-logs:
    driver: local