version: '3.8'

services:
  # API Service (connects to WebApp's nginx)
  api:
    build: .
    container_name: ollo-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - Jwt__SecretKey=${JWT_SECRET_KEY}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - DB_PASSWORD=${DB_PASSWORD}
    expose:
      - "5000"  # Internal only, accessible via Docker network
    networks:
      - ollolifestylewebapp_frontend
    volumes:
      - ./logs/api:/app/Logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ollolifestylewebapp_frontend:
    external: true

volumes:
  logs:
    driver: local