version: '3.8'

services:
  api:
    build: .
    container_name: ollo-api
    restart: unless-stopped
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - Jwt__SecretKey=${Jwt__SecretKey}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    volumes:
      - ./logs/api:/app/Logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  frontend:
    external: true
    name: ollo-lifestyle-webapp_frontend

volumes:
  logs: