version: '3.8'

services:
  api:
    build: .
    container_name: ollo-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - JWT_SECRET_KEY=tX7@zK9!eA#dF$wL2pB^JgQmRvYxUoTiN1sC3hVbEkMzLaGd
      - Jwt__SecretKey=tX7@zK9!eA#dF$wL2pB^JgQmRvYxUoTiN1sC3hVbEkMzLaGd
      - ConnectionStrings__DefaultConnection=Server=192.168.50.1,1433;Database=OlloLifestyleAPI_Master;User Id=sa;Password=Sa@123#2025;MultipleActiveResultSets=true;TrustServerCertificate=true;Encrypt=true;
    expose:
      - "5000"
    networks:
      - frontend
    extra_hosts:
      - "host.docker.internal:192.168.50.1"
    volumes:
      - ./logs/api:/app/Logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  frontend:
    external: true
    name: ollo-lifestyle-webapp_frontend

volumes:
  logs: